Face Detection on saved file 

#### importing the libraries

In [1]:
import numpy as np
import os
import cv2 as cv

#### face detection 

In [2]:
def FaceDetection(test_img):
    gray_img = cv.cvtColor(test_img,cv.COLOR_BGR2GRAY)
    face_haar_cascade = cv.CascadeClassifier('D:\Internship ML\Projects\Open cv\haarcascade_frontalface_default.xml')
    faces = face_haar_cascade.detectMultiScale(gray_img,scaleFactor=1.3,minNeighbors=5) #classifier has many dependencies
    return faces,gray_img
test_img = cv.imread('D:\Internship ML\Projects\Open cv\Face images\img5.jpg')
face_detected,gray_img = FaceDetection(test_img)
print('Face Detected',face_detected)

Face Detected [[ 868  605  269  269]
 [ 627  250  286  286]
 [ 186  109  459  459]
 [1056  106  296  296]
 [1379  354  476  476]]


In [4]:
for (x,y,w,h) in face_detected:
    cv.rectangle(test_img,(x,y),(x+w,y+h),(180,0,100),thickness=4)
    pass
resized_img = cv.resize(test_img,(900,700))
cv.imshow("Face Detection Window",resized_img)
cv.waitKey(0)
cv.destroyAllWindows()